[package]
name = "ringbuffer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
event-listener = "5.4.2"

[dependencies.uuid]
version = "1.26.0"
# Lets you generate random UUIDs
features = [
    "v4",
]